# Generated by Django 6.0.1 on 2026-01-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("house_number", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=15)),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
